@baseUrl = http://localhost:3000


### List all messages
GET {{baseUrl}}/messages


### Create a new message
POST {{baseUrl}}/messages
Content-Type: application/json

{
    "content": "Hi there!"
}


### Get a particular message
GET {{baseUrl}}/messages/:id