### Create a new user
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "matkhau"
}


### Find a particular user with a given id
GET {{baseUrl}}/auth/6


### Find all users with a given email
GET {{baseUrl}}/auth?email=example@gmail.com


### Delete a user given id
DELETE {{baseUrl}}/auth/5

### Update a user given id
PATCH {{baseUrl}}/auth/3
Content-Type: application/json

{
    "email": "example2@gmail.com",
    "password": "matkhau"
}