### Create a new user
@email = tranvanhung@example.com
@password = SecurePass123!
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}


### Find a particular user with a given ID
@id = 1
GET {{baseUrl}}/auth/{{id}}


### Find all users with a given email
@email = tranvanhung@example.com
GET {{baseUrl}}/auth?email={{email}}